name: CI

on:
  push:
    branches:
      - main  # Ejecuta pruebas al hacer push en la rama 'main'

jobs:
  ruff:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.13']  # Puedes cambiar las versiones según necesites

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}  # Configura la versión de Python desde la matriz

      - name: Install Ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run Ruff
        run: ruff check .

      - name: Display Python version
        run: python --version
